### ISSUE TITLE
Unused AUR dependencies?

### ISSUE THREAD

**Issue by chocolateboy** [numToStr/snm#75]
The [AUR package](https://aur.archlinux.org/packages.php?ID=907606) lists the following dependencies:

- pacman (< 6)
- sudo
- git

Why are these needed? I can't see any reference to them in the [PKGBUILD](https://github.com/numToStr/snm/blob/v0.6.0/.aur/PKGBUILD), which just downloads a precompiled binary.

**Comment by numToStr** [comment]
Thanks for pointing it out. I haven't put that much thought when I was publishing on aur. Now If I think then the only thing that is required is maybe `tar` because all the binaries are tar archived.
